security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Participant
                property: mail
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: app_login
                check_path: app_login
            guard:
                authenticators:
                    - App\Security\AppCustonAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 #
                path:     /

    encoders:
        App\Entity\Participant:
            algorithm: auto

    access_control:
     - { path: ^/participant, roles: ROLE_USER }
     - { path: ^/ville, roles: ROLE_ADMIN }
